### ISSUE TITLE
.env file for default configuration

### ISSUE THREAD

**Issue by metalmatze** [tomazk/envcfg#7]
Hey, I really like the approach not to use `os.Getenv()` everywhere but to Unmarshal to a struct! Great idea.

I'm just missing the `.env` file support. Is there a reason I'm not aware of, that it's not there?
It wouldn't be that hard to add `.env` support, right?

Thanks!

**Comment by tomazk** [comment]
@MetalMatze No specific reason on why it's not supported. I'm just not a dotenv user.

Please send me a pull request, if you'd like to see support for that.

**Comment by tomazk** [comment]
BTW: please feel free to reopen the issue if you'd like to discuss this further
